import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Topbar from '../components/topbar/topbar';
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";
import Video from "@/components/video/video";
import EhphWhy from "@/components/ehphwhy/ehphwhy";
   
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (<>
	<Head>
	<title>EHP - HASNAOUI</title>
	<meta name="description" content="Generated by create next app" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<link rel="icon" href="/logozoom.PNG" />
  </Head>
  <main style={{padding:'0'}}>
 
 <Topbar/>

 <Navbar/>

<EhphWhy/>
 <Video/>
 <Footer/>
     </main>
</>
  );
}
